2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_122918-o2truhpx/logs/debug.log
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_122918-o2truhpx/logs/debug-internal.log
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fbfddf91b70>
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:29:18,765 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:29:18,766 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:29:18,771 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:29:18,779 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:29:18,798 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:29:18,798 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:29:18,798 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:29:18,892 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:29:19,487 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-10 12:29:19,719 ERROR   MainThread:97150 [wandb_init.py:init():1172] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-10 12:29:48,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:29:48,850 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:29:48,851 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_122948-vb59ys19/logs/debug.log
2023-07-10 12:29:48,851 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_122948-vb59ys19/logs/debug-internal.log
2023-07-10 12:29:48,851 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:29:48,852 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:29:48,852 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:29:48,852 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:29:48,872 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:29:48,875 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:29:48,888 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:29:48,888 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:29:48,888 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:29:48,937 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:29:49,599 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-10 12:29:49,667 ERROR   MainThread:97150 [wandb_init.py:init():1172] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-10 12:30:19,848 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_123019-qgl73v89/logs/debug.log
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_123019-qgl73v89/logs/debug-internal.log
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:30:19,849 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:30:19,851 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:30:19,852 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:30:19,862 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:30:19,863 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:30:19,863 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:30:19,924 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:31:20,257 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:31:20,332 ERROR   MainThread:97150 [wandb_init.py:init():1172] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:35:54,496 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:35:54,497 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:35:54,497 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:35:54,497 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:35:54,497 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:35:54,497 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_123554-z6ez1rs0/logs/debug.log
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_123554-z6ez1rs0/logs/debug-internal.log
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:35:54,498 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:35:54,500 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:35:54,501 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:35:54,514 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:35:54,515 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:35:54,515 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:35:54,595 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:35:56,572 INFO    MainThread:97150 [wandb_run.py:_on_init():2173] communicating current version
2023-07-10 12:35:56,742 WARNING MsgRouterThr:97150 [router.py:message_loop():77] message_loop has been closed
2023-07-10 12:36:26,700 INFO    MainThread:97150 [wandb_init.py:init():789] starting run threads in backend
2023-07-10 12:36:56,928 INFO    MainThread:97150 [wandb_run.py:_console_start():2152] atexit reg
2023-07-10 12:36:56,931 INFO    MainThread:97150 [wandb_run.py:_redirect():2007] redirect: SettingsConsole.WRAP_RAW
2023-07-10 12:36:56,931 INFO    MainThread:97150 [wandb_run.py:_redirect():2072] Wrapping output streams.
2023-07-10 12:36:56,932 INFO    MainThread:97150 [wandb_run.py:_redirect():2097] Redirects installed.
2023-07-10 12:36:56,934 INFO    MainThread:97150 [wandb_init.py:init():830] run started, returning control to user process
2023-07-10 12:45:16,325 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_124516-ddnao1n7/logs/debug.log
2023-07-10 12:45:16,327 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_124516-ddnao1n7/logs/debug-internal.log
2023-07-10 12:45:16,328 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:45:16,328 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:45:16,328 INFO    MainThread:97150 [wandb_init.py:init():571] re-initializing run, found existing run on stack: z6ez1rs0
2023-07-10 12:45:16,332 INFO    MainThread:97150 [wandb_run.py:_finish():1887] finishing run ishevchuk/NightSky/z6ez1rs0
2023-07-10 12:45:16,332 INFO    MainThread:97150 [wandb_run.py:_atexit_cleanup():2121] got exitcode: 0
2023-07-10 12:45:16,333 INFO    MainThread:97150 [wandb_run.py:_restore():2104] restore
2023-07-10 12:45:16,334 INFO    MainThread:97150 [wandb_run.py:_restore():2110] restore done
2023-07-10 12:46:52,864 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:46:52,866 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:46:52,872 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:46:52,876 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:46:52,898 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:46:52,899 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:46:52,899 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:46:52,979 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:47:53,323 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:47:53,407 ERROR   MainThread:97150 [wandb_init.py:init():1172] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:49:19,342 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_124919-4b3s8nq3/logs/debug.log
2023-07-10 12:49:19,343 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_124919-4b3s8nq3/logs/debug-internal.log
2023-07-10 12:49:19,344 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:49:19,344 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:49:19,344 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:49:19,344 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:49:19,345 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:49:19,346 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:49:19,355 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:49:19,356 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:49:19,356 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:49:19,413 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:50:19,750 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:50:19,827 ERROR   MainThread:97150 [wandb_init.py:init():1172] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:54:55,246 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-10 12:54:55,247 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Configure stats pid to 97150
2023-07-10 12:54:55,247 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/.config/wandb/settings
2023-07-10 12:54:55,247 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from /Users/ishevchuk/Desktop/NightSky/wandb/settings
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_init.py:_log_setup():507] Logging user logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_125455-rg6nfqbd/logs/debug.log
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/ishevchuk/Desktop/NightSky/wandb/run-20230710_125455-rg6nfqbd/logs/debug-internal.log
2023-07-10 12:54:55,248 INFO    MainThread:97150 [wandb_init.py:init():547] calling init triggers
2023-07-10 12:54:55,249 INFO    MainThread:97150 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-10 12:54:55,249 INFO    MainThread:97150 [wandb_init.py:init():596] starting backend
2023-07-10 12:54:55,249 INFO    MainThread:97150 [wandb_init.py:init():600] setting up manager
2023-07-10 12:54:55,250 INFO    MainThread:97150 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-10 12:54:55,251 INFO    MainThread:97150 [wandb_init.py:init():606] backend started and connected
2023-07-10 12:54:55,262 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-10 12:54:55,263 INFO    MainThread:97150 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-10 12:54:55,264 INFO    MainThread:97150 [wandb_init.py:init():705] updated telemetry
2023-07-10 12:54:55,323 INFO    MainThread:97150 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-10 12:55:55,622 ERROR   MainThread:97150 [wandb_init.py:init():764] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-07-10 12:55:55,704 ERROR   MainThread:97150 [wandb_init.py:init():1172] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/ishevchuk/anaconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
